# Generated by Django 3.2.7 on 2021-10-08 21:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('setores', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('name', models.CharField(default='none informed', max_length=256)),
                ('data_nascimento', models.DateTimeField(blank=True, null=True)),
                ('cidade', models.CharField(default='none informed', max_length=128)),
                ('estado', models.CharField(default='none informed', max_length=128)),
                ('num_identificacao', models.CharField(max_length=8, primary_key=True, serialize=False, unique=True)),
                ('tipo_usuario', models.CharField(choices=[('ALU', 'Aluno'), ('FUN', 'Funcionario')], max_length=3)),
                ('setor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='setores.setor')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
