# Generated by Django 3.2.7 on 2021-09-30 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aluno',
            name='num_matricula',
            field=models.CharField(max_length=16, unique=True),
        ),
        migrations.AlterField(
            model_name='funcionario',
            name='num_funcional',
            field=models.CharField(max_length=16, unique=True),
        ),
    ]
