# Generated by Django 3.2.7 on 2021-11-25 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0005_alter_usuario_data_nascimento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='tipo_usuario',
            field=models.CharField(choices=[('ALU', 'Aluno'), ('FUN', 'Funcionario'), ('ADM', 'Administrador'), ('GES', 'Gestor')], max_length=3),
        ),
    ]
