# Generated by Django 3.2.7 on 2021-11-10 05:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ListaSintomas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('falta_ar', models.BooleanField()),
                ('cansaco', models.BooleanField()),
                ('febre', models.BooleanField()),
                ('calafrios', models.BooleanField()),
                ('tosse', models.BooleanField()),
                ('dor_garganta', models.BooleanField()),
                ('dor_cabeca', models.BooleanField()),
                ('dor_peito', models.BooleanField()),
                ('perda_olfato', models.BooleanField()),
                ('perda_paladar', models.BooleanField()),
                ('diarreia', models.BooleanField()),
                ('coriza', models.BooleanField()),
                ('espirros', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='EstadoSaude',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('OK', 'Bem'), ('NOK', 'Não muito bem')], max_length=12)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('sintomas', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='saude.listasintomas')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
