# Generated by Django 3.2.7 on 2021-11-23 08:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('saude', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sintoma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=280)),
            ],
        ),
        migrations.RemoveField(
            model_name='estadosaude',
            name='sintomas',
        ),
        migrations.CreateModel(
            name='EstadoSintomaItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('apresenta', models.BooleanField()),
                ('estado_saude', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='saude.estadosaude')),
                ('nome_sintoma', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='saude.sintoma')),
            ],
        ),
    ]
