# Generated by Django 3.2.7 on 2021-11-23 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saude', '0003_rename_nome_sintoma_estadosintomaitem_sintoma'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estadosaude',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
